# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from os import stat
from PyQt5 import QtCore, QtGui, QtWidgets
import api

import home
import precautions 
import statistics
import statistics
import latest 
import helpline 
import Vaccination 

class Ui_home(object):

    def homep(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = home.Ui_home()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def latestp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = latest.Ui_latest()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def precs(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = precautions.Ui_precautions()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def statsp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = statistics.Ui_statistics()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def vaccp(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Vaccination.Ui_vcc()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def helplinep(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = helpline.Ui_HelpLines()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(804, 600)
        home.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.label_2.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        # self.label_2.mousePressEvent=self.homep
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 111, 31))
        self.label_3.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.mousePressEvent=self.precs
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 101, 31))
        self.label_4.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.mousePressEvent=self.latestp
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.label_5.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.mousePressEvent=self.statsp
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 71, 81))
        self.label_6.setMouseTracking(True)
        self.label_6.setStyleSheet("background:none")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("cov.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.label_7.setStyleSheet("color:White;\n"
"Font-size:15px;\n"
"letter-spacing:0.5px;\n"
"background:none")
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 140, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setStyleSheet("border:1px solid Blue;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setStyleSheet("border:1px solid #D86CF7;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setStyleSheet("border:1px solid green;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("border:1px solid red;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(130, 170, 531, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setStyleSheet("border:1px solid Blue;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setStyleSheet("border:1px solid #D86CF7")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setStyleSheet("border:1px solid green\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setStyleSheet("border:1px solid red\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        # self.label_13.setText(api.response1['data']['deaths'])
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(30, 270, 101, 31))
        self.label_15.setStyleSheet("color:white;\n"
"background:none;\n"
"font-size:14px")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 270, 151, 31))
        self.comboBox.setStyleSheet("border:2px solid Green;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"color: Black;\n"
"background:none;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(160, 320, 481, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)


        
       
        
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 250, 201, 41))
        self.pushButton_3.setStyleSheet("QPushButton{border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    \n"
"background-color:#08A61F;\n"
"\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"font-size:21px;\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: #0C9A20;\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.vaccp)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label_16.setStyleSheet("")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image (2).png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 110, 101, 41))
        self.pushButton_2.setStyleSheet("QPushButton{border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    \n"
"    background-color: rgb(255, 98, 101);\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"font-size:18px;\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(255, 0, 4);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.helplinep)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(630, 70, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;\n"
"background:none;\nfont-size:12px")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(680, 10, 61, 61))
        self.label_17.setStyleSheet("background:none;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("User icon.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_16.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label_15.raise_()
        self.comboBox.raise_()
        self.tableWidget.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 22))
        self.menubar.setObjectName("menubar")
        home.setMenuBar(self.menubar)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Home"))
        self.label_2.setWhatsThis(_translate("home", "<html><head/><body><p>winc </p></body></html>"))
        self.label_2.setText(_translate("home", "Home"))
        self.label_3.setText(_translate("home", "Precaution"))
        self.label_4.setText(_translate("home", "Latest"))
        self.label_5.setText(_translate("home", "Stats"))
        self.label_7.setText(_translate("home", "|| Covid Tracker ||"))
        self.label_10.setText(_translate("home", "Total Cases"))
        self.label_9.setText(_translate("home", "Active Cases"))
        self.label_8.setText(_translate("home", "Recovered"))
        self.label.setText(_translate("home", "Deaths"))
        self.label_14.setText(_translate("home", f"{api.response1[0]['TotalCases']}"))
        self.label_12.setText(_translate("home", f"{api.response1[0]['ActiveCases']}"))
        self.label_11.setText(_translate("home", f"{api.response1[0]['TotalRecovered']}"))
        self.label_13.setText(_translate("home", f"{api.response1[0]['TotalDeaths']}"))
        self.label_15.setText(_translate("home", "Show Data:"))
        self.comboBox.setItemText(0, _translate("home", "Country Wise"))
        self.comboBox.setItemText(1, _translate("home", "State Wise"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("home", "USA"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("home", "India"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("home", "France"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("home", "Brazil"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("home", "Germany"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("home", "UK"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("home", "Russia"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("home", "Germany"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("home", "Country"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("home", "Total Cases"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("home", "Recovered"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("home", "Deaths"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("home", f"{api.response1[2]['TotalCases']}"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("home", f"{api.response1[2]['TotalRecovered']}"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("home", f"{api.response1[2]['TotalDeaths']}"))

        item = self.tableWidget.item(1, 0)
        item.setText(_translate("home", f"{api.response1[3]['TotalCases']}"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("home", f"{api.response1[3]['TotalRecovered']}"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("home", f"{api.response1[3]['TotalDeaths']}"))
        
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("home", f"{api.response1[5]['TotalCases']}"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("home", f"{api.response1[5]['TotalRecovered']}"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("home", f"{api.response1[5]['TotalDeaths']}"))
        
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("home", f"{api.response1[4]['TotalCases']}"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("home", f"{api.response1[4]['TotalRecovered']}"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("home", f"{api.response1[4]['TotalDeaths']}"))

        item = self.tableWidget.item(4, 0)
        item.setText(_translate("home", f"{api.response1[6]['TotalCases']}"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("home", f"{api.response1[6]['TotalRecovered']}"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("home", f"{api.response1[6]['TotalDeaths']}"))
        
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("home", f"{api.response1[7]['TotalCases']}"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("home", f"{api.response1[7]['TotalRecovered']}"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("home", f"{api.response1[7]['TotalDeaths']}"))

        item = self.tableWidget.item(6, 0)
        item.setText(_translate("home", f"{api.response1[8]['TotalCases']}"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("home", f"{api.response1[8]['TotalRecovered']}"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("home", f"{api.response1[8]['TotalDeaths']}"))


        item = self.tableWidget.item(7, 0)
        item.setText(_translate("home", f"{api.response1[9]['TotalCases']}"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("home", f"{api.response1[9]['TotalRecovered']}"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("home", f"{api.response1[9]['TotalDeaths']}"))

        
        
        # item = self.tableWidget.item(1, 1)
        # item.setText(_translate("home", "23"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("home", "Vaccination Details"))
        self.pushButton_2.setText(_translate("home", "Help Lines"))
        self.label_18.setText(_translate("home", "Welcome, Anurag Yadav"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(home)
    home.show()
    sys.exit(app.exec_())
