# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'latest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import home
import precautions 
import statistics
import statistics
import helpline
import symptoms

class Ui_latest(object):
    

    def homep(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = home.Ui_home()
        self.ui.setupUi(self.window)
        self.window.show()
        # latest.close()

    def precs(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = precautions.Ui_precautions()
        self.ui.setupUi(self.window)
        self.window.show()
        # latest.close()

    def statsp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = statistics.Ui_statistics()
        self.ui.setupUi(self.window)
        self.window.show()
        # latest.close()

    def helplinep(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = helpline.Ui_HelpLines()
        self.ui.setupUi(self.window)
        self.window.show()
        # latest.close()

    def symptomsp(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =symptoms.Ui_symptoms()
        self.ui.setupUi(self.window)
        self.window.show()
        # latest.close()

    def setupUi(self, latest):
        latest.setObjectName("latest")
        latest.resize(802, 590)
        latest.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(latest)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.label_2.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.mousePressEvent=self.homep
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 111, 31))
        self.label_3.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.mousePressEvent = self.precs
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 101, 31))
        self.label_4.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        # self.label_4.mousePressEvent = self.latestp
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.label_5.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.mousePressEvent = self.statsp
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 120, 101, 41))
        self.pushButton_2.setStyleSheet("QPushButton{border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    \n"
"    background-color: rgb(255, 98, 101);\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(255, 0, 4);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.helplinep)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 71, 81))
        self.label_6.setMouseTracking(True)
        self.label_6.setStyleSheet("background:none")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("cov.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.label_7.setStyleSheet("color:White;\n"
"Font-size:15px;\n"
"letter-spacing:0.5px;\n"
"background:none")
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.label_16.setStyleSheet("")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image (2).png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 180, 321, 31))
        self.label_8.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border-radius:15px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 360, 51, 21))
        self.label_9.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(240, 110, 321, 41))
        self.label1.setStyleSheet("color: Black;\n"
"Font-size:20px;\n"
"letter-spacing:1.2px;\n"
"border-radius:15px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"")
        self.label1.setObjectName("label1")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 360, 51, 21))
        self.label_10.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(640, 360, 51, 21))
        self.label_11.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 530, 51, 21))
        self.label_12.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"")
        self.label_12.setObjectName("label_12")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(660, 170, 101, 41))
        self.pushButton4.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    background-color: rgb(255, 149, 255);\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(255, 73, 255);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton4.clicked.connect(self.symptomsp)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(650, 530, 51, 21))
        self.label_13.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(120, 530, 51, 21))
        self.label_14.setStyleSheet("color: Black;\n"
"Font-size:10px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;\n"
"\n"
"")
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 230, 181, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223002.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(56, 402, 181, 121))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223210.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(310, 230, 191, 121))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223054.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(576, 232, 181, 121))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223144.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(320, 400, 181, 121))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223232.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(580, 400, 181, 121))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Screenshot 2022-03-15 223251.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(630, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"background:none;\nfont-size:12px")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(680, 20, 61, 61))
        self.label_22.setStyleSheet("background:none;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("User icon.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(240, 150, 331, 20))
        self.label_23.setStyleSheet("background:none;\n"
"border-top:2px solid cyan;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(30, 210, 331, 20))
        self.label_24.setStyleSheet("background:none;\n"
"border-top:2px solid cyan;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_16.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label1.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.pushButton4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_17.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        latest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(latest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 22))
        self.menubar.setObjectName("menubar")
        latest.setMenuBar(self.menubar)

        self.retranslateUi(latest)
        QtCore.QMetaObject.connectSlotsByName(latest)

    def retranslateUi(self, latest):
        _translate = QtCore.QCoreApplication.translate
        latest.setWindowTitle(_translate("latest", "Latest Updates/Guidelines"))
        self.label_2.setText(_translate("latest", "Home"))
        self.label_3.setText(_translate("latest", "Precaution"))
        self.label_4.setText(_translate("latest", "Latest"))
        self.label_5.setText(_translate("latest", "Stats"))
        self.pushButton_2.setText(_translate("latest", "Help Lines"))
        self.label_7.setText(_translate("latest", "|| Covid Tracker ||"))
        self.label_8.setText(_translate("latest", "<html><head/><body><p align=\"center\">Government Updates / Announcements</p></body></html>"))
        self.label_9.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.label1.setText(_translate("latest", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Latest Updates/Guidelines</span></p></body></html>"))
        self.label_10.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.label_11.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.label_12.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.pushButton4.setText(_translate("latest", "Symptons"))
        self.label_13.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.label_14.setText(_translate("latest", "<html><head/><body><p align=\"center\">PDF</p></body></html>"))
        self.label_21.setText(_translate("latest", "Welcome, Anurag Yadav"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    latest = QtWidgets.QMainWindow()
    ui = Ui_latest()
    ui.setupUi(latest)
    latest.show()
    sys.exit(app.exec_())
