# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import mysql.connector as mc
import home
import Signup


class Ui_login(object):

    # def open_home(self):
    #

    def logincheck(self):
        # print("Login button Clicked")
        username = self.uname.text()
        passwrd = self.paaswd.text()



        conn = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="covid tracker"
        )
        # print("Connected")
        cur = conn.cursor()
        query = "SELECT uname,pass from users where uname " \
                "like '" + username + "'and pass like '" \
                + passwrd + "'"

        # print("Query")

        cur.execute(query)

        # print("AQ")
        result = cur.fetchone()

        if (result == None):
            if username == "":
                self.label_3.setText("Enter Your Username!!")

            elif passwrd == "":
                self.label_3.setText("Enter Your Password!!")
            
            else:
                self.label_3.setText("Invalid Credentials!!")

        else:
            fname=self.uname.text()
            self.window = QtWidgets.QMainWindow()
            self.ui = home.Ui_home()
            self.ui.setupUi(self.window)
            # self.login.close()
            self.window.show()
            # self.login.close()
            
            print("Logged in successfully!!")
            
        
    def resetbtn(self):
        self.uname.setText("")
        self.paaswd.setText("")
        

    def signp(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Signup.Ui_signup()
        self.ui.setupUi(self.window)
        # self.login.close()
        self.window.show()
        login.close()
        

    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(480, 525)
        login.setStyleSheet(
            "background:qlineargradient(spread:pad, x1:1, y1:0.960227, x2:0.284091, y2:0.511, stop:0 rgba(0, 255, 168, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 120, 180, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;")
        self.label.setObjectName("label")
        self.uname = QtWidgets.QLineEdit(self.centralwidget)
        self.uname.setGeometry(QtCore.QRect(120, 140, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uname.setFont(font)
        self.uname.setStyleSheet("QLineEdit{\n"
                                 "    background: #E5C8F3;\n"
                                 "    border:2px solid purple;\n"
                                 "    border-radius:15px;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:focus{\n"
                                 "    border:2px solid #F49D2E;\n"
                                 "    background: #F3D7B4;\n"
                                 "    border-radius:15px;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.uname.setObjectName("uname")
        self.paaswd = QtWidgets.QLineEdit(self.centralwidget)
        self.paaswd.setGeometry(QtCore.QRect(120, 230, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paaswd.setFont(font)
        self.paaswd.setStyleSheet("QLineEdit{\n"
                                  "    background: #E5C8F3;\n"
                                  "    border:2px solid purple;\n"
                                  "    border-radius:15px;\n"
                                  "}\n"
                                  "\n"
                                  "QLineEdit:focus{\n"
                                  "    border:2px solid #F49D2E;\n"
                                  "    background: #F3D7B4;\n"
                                  "    border-radius:15px;\n"
                                  "}")
        self.paaswd.setText("")
        self.paaswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.paaswd.setObjectName("paaswd")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 180, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:none;")
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 290, 180, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;\ncolor:red;")
        self.label_3.setObjectName("label_3")

        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setGeometry(QtCore.QRect(180, 310, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginbtn.setFont(font)
        self.loginbtn.setStyleSheet("QPushButton{\n"
                                    "    background-color:#F0BDE6;\n"
                                    "    border: 2px solid black;\n"
                                    "    border-radius:15px;\n"
                                    "  "
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color:#F1D5EB;\n"
                                    "    border: 2px solid black;\n"
                                    "    border-radius:15px;\n"

                                    "}\n"
                                    "\n"
                                    "")
        self.loginbtn.setObjectName("loginbtn")
        self.loginbtn.clicked.connect(self.logincheck)
        #         self.reserpass = QtWidgets.QPushButton(self.centralwidget)
        #         self.reserpass.setGeometry(QtCore.QRect(120, 280, 111, 31))
        #         self.reserpass.setStyleSheet("QPushButton{\n"
        # "    background-color:none;\n"
        # "    border:2px solid black;\n"
        # "    border-radius:15px;\n"
        # "}\n"
        # "QPushButton:hover{\n"
        # "    background-color:#E1E7F0;\n"
        # "    border: 2px solid black;\n"
        # "    border-radius:15px;\n"
        # "}\n"
        # "")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 415, 170, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;")
        self.label_4.setObjectName("label_4")
        self.lsignup = QtWidgets.QPushButton(self.centralwidget)
        self.lsignup.setGeometry(QtCore.QRect(20, 440, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lsignup.setFont(font)
        self.lsignup.setStyleSheet("QPushButton{\n"
                                   "    background-color:#7AA9F0;\n"
                                   "    border: 2px solid black;\n"
                                   "    border-radius:15px;\n"

                                   "\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    background-color:#A8C7F5;\n"
                                   "    border: 2px solid black;\n"
                                   "    border-radius:15px;\n"

                                   "}\n"
                                   "")
        self.lsignup.setObjectName("lsignup")
        self.lsignup.clicked.connect(self.signp)
        self.lreset = QtWidgets.QPushButton(self.centralwidget)
        self.lreset.setGeometry(QtCore.QRect(370, 80, 71, 31))
        self.lreset.setStyleSheet("QPushButton{\n"
                                  "    background-color:none;\n"
                                  "    border:2px solid black;\n"
                                  "    border-radius:15px;\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "    background-color:#E1E7F0;\n"
                                  "    border: 2px solid black;\n"
                                  "    border-radius:15px;\n"
                                  "}")
        self.lreset.setObjectName("lreset")
        self.lreset.clicked.connect(self.resetbtn)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 481, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 58, 255, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login || Covid Tracker Application"))
        self.label.setText(_translate("login", "Enter Your Username"))
        self.label_2.setText(_translate("login", "Enter Your Password"))
        self.loginbtn.setText(_translate("login", "Login"))
        # self.reserpass.setText(_translate("login", "Reset Password"))
        self.label_3.setText(_translate("login", ""))
        self.label_4.setText(_translate("login", "New User? Sign up"))
        self.lsignup.setText(_translate("login", "Sign Up"))
        self.lreset.setText(_translate("login", "Reset"))
        self.label_5.setText(_translate("login", "Login"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
