# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'precautions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import home
import precautions 
import statistics
import helpline
import mythbusters
import latest

class Ui_precautions(object):

    def homep(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = home.Ui_home()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def latestp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = latest.Ui_latest()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def precs(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = precautions.Ui_precautions()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def statsp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = statistics.Ui_statistics()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()\

    def helplinep(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = helpline.Ui_HelpLines()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def myth(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = mythbusters.Ui_myth()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def setupUi(self, precautions):
        precautions.setObjectName("precautions")
        precautions.resize(799, 580)
        precautions.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(precautions)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.label_2.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.mousePressEvent=self.homep
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 111, 31))
        self.label_3.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 101, 31))
        self.label_4.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.mousePressEvent=self.latestp
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.label_5.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.mousePressEvent=self.statsp
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 71, 81))
        self.label_6.setMouseTracking(True)
        self.label_6.setStyleSheet("background:none")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("cov.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.label_7.setStyleSheet("color:White;\n"
"Font-size:15px;\n"
"letter-spacing:0.5px;\n"
"background:none")
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label_16.setStyleSheet("")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image (2).png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 100, 161, 31))
        self.label.setStyleSheet("color: Black;\n"
"Font-size:25px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(645, 160, 136, 41))
        self.label_8.setStyleSheet("    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"   font: 75 10pt \"Times New Roman\";\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;")
        self.label_8.setObjectName("label_8")
        self.label_8.mousePressEvent=self.myth
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 160, 191, 131))
        self.label_9.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("1.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 280, 171, 16))
        self.label_10.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(190, 290, 241, 221))
        self.label_11.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("2.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(130, 430, 521, 51))
        self.label_12.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(170, 470, 231, 16))
        self.label_13.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(400, 150, 231, 191))
        self.label_14.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("3.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(390, 300, 241, 16))
        self.label_15.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(420, 320, 181, 16))
        self.label_17.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(530, 330, 201, 171))
        self.label_18.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("4.png"))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(490, 480, 311, 20))
        self.label_19.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(280, 130, 251, 20))
        self.label_20.setStyleSheet("background:none;\n"
"border-top:2px solid cyan;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 110, 101, 41))
        self.pushButton_2.setStyleSheet("QPushButton{border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    \n"
"    background-color: rgb(255, 98, 101);\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(255, 0, 4);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.helplinep)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(620, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"background:none;\nfont-size:12px;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(670, 20, 61, 61))
        self.label_22.setStyleSheet("background:none;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("User icon.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_16.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.pushButton_2.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        precautions.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(precautions)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 22))
        self.menubar.setObjectName("menubar")
        precautions.setMenuBar(self.menubar)

        self.retranslateUi(precautions)
        QtCore.QMetaObject.connectSlotsByName(precautions)

    def retranslateUi(self, precautions):
        _translate = QtCore.QCoreApplication.translate
        precautions.setWindowTitle(_translate("precautions", "Precautions"))
        self.label_2.setText(_translate("precautions", "Home"))
        self.label_3.setText(_translate("precautions", "Precaution"))
        self.label_4.setText(_translate("precautions", "Latest"))
        self.label_5.setText(_translate("precautions", "Stats"))
        self.label_7.setText(_translate("precautions", "|| Covid Tracker ||"))
        self.label.setText(_translate("precautions", "Precautions"))
        self.label_8.setText(_translate("precautions", "Myth-Busters"))
        self.label_10.setText(_translate("precautions", "WEAR FACE MASK"))
        self.label_12.setText(_translate("precautions", " WASH YOUR HANDS FREQUENTLY "))
        self.label_13.setText(_translate("precautions", "WITH SOAP AND WATER "))
        self.label_15.setText(_translate("precautions", "DO NOT TOUCH YOUR EYES"))
        self.label_17.setText(_translate("precautions", "WITH DIRTY HANDS"))
        self.label_19.setText(_translate("precautions", "USE TISSUE WHEN SNEEZE/COUGH"))
        self.pushButton_2.setText(_translate("precautions", "Help Lines"))
        self.label_21.setText(_translate("precautions", "Welcome, Anurag Yadav"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    precautions = QtWidgets.QMainWindow()
    ui = Ui_precautions()
    ui.setupUi(precautions)
    precautions.show()
    sys.exit(app.exec_())
