f.tableWidget.isSortingEnabled()
        # self.tableWidget.setSortingEnabled(False)
        # item = self.tableWidget.item(0, 0)
        # item.setText(_translate("home", "1234567"))
        # item = self.tableWidget.item(1, 1)
        # item.setText(_translate("home", "23"))
        # self.tableWidget.setSortingEnabled(__sortingEnabled)