# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vaccination.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import home
import precautions 
import statistics
import statistics
import helpline
import latest


class Ui_vcc(object):

    def homep(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = home.Ui_home()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def latestp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui = latest.Ui_latest()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def precs(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui =precautions.Ui_precautions()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()

    def statsp(self,event):
        self.window = QtWidgets.QMainWindow()
        self.ui =statistics.Ui_statistics()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()\

    def helplinep(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =helpline.Ui_HelpLines()
        self.ui.setupUi(self.window)
        self.window.show()
        # home.close()


    def setupUi(self, vcc):
        vcc.setObjectName("vcc")
        vcc.resize(804, 603)
        vcc.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(vcc)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.label_2.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.mousePressEvent=self.homep
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 111, 31))
        self.label_3.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.mousePressEvent=self.precs
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 101, 31))
        self.label_4.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.mousePressEvent=self.latestp
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.label_5.setStyleSheet("color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.mousePressEvent=self.statsp
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 110, 101, 41))

        self.pushButton_2.setStyleSheet("QPushButton{border-radius:20px;\n"
"font: 12pt \"Times New Roman\";\n"
"    \n"
"    background-color: rgb(255, 98, 101);\n"
"\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(255, 0, 4);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{    background: #F8B97A;\n"
"    border:2px solid black;\n"
"    border-radius:15px;\n"
"    color:Black;\n"
"    font-size: 15px;\n"
"    letter-spacing: 0.5px;\n"
"    font-family: \'Lato\';\n"
"    font-weight: 200;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.helplinep)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 71, 81))
        self.label_6.setMouseTracking(True)
        self.label_6.setStyleSheet("background:none")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("cov.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.label_7.setStyleSheet("color:White;\n"
"Font-size:15px;\n"
"letter-spacing:0.5px;\n"
"background:none")
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label_16.setStyleSheet("")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image (2).png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 260, 111, 31))
        self.label_8.setStyleSheet("color:white;\n"
"background:none;\n"
"font-size:14px\n"
"")
        self.label_8.setObjectName("label_8")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(200, 260, 141, 31))
        self.comboBox1.setStyleSheet("border:2px solid Green;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"color: Black;\n"
"background:none;\n"
"")
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(250, 110, 271, 41))
        self.label1.setStyleSheet("color: Black;\n"
"Font-size:20px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid #aa55ff;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;")
        self.label1.setObjectName("label1")
        self.tableWidget1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget1.setGeometry(QtCore.QRect(80, 300, 651, 191))
        self.tableWidget1.setMinimumSize(QtCore.QSize(651, 191))
        self.tableWidget1.setMaximumSize(QtCore.QSize(651, 16777215))
        self.tableWidget1.setStyleSheet("border:1px solid Blue;")
        self.tableWidget1.setLineWidth(3)
        self.tableWidget1.setMidLineWidth(2)
        self.tableWidget1.setAutoScrollMargin(16)
        self.tableWidget1.setAlternatingRowColors(True)
        self.tableWidget1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget1.setRowCount(6)
        self.tableWidget1.setColumnCount(4)
        self.tableWidget1.setObjectName("tableWidget1")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget1.setItem(5, 3, item)
        self.tableWidget1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget1.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget1.verticalHeader().setDefaultSectionSize(33)
        self.tableWidget1.verticalHeader().setMinimumSectionSize(23)
        self.tableWidget1.verticalHeader().setSortIndicatorShown(False)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 510, 341, 31))
        self.label_11.setStyleSheet("border:1px solid #ff00ff;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px\n"
"\n"
"\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(170, 550, 101, 21))
        self.pushButton4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 222, 255);\n"
"\n"
"border-radius:10px;\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 83, 255);\n"
"\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"{\n"
"color: Black;\n"
"Font-size:15px;\n"
"letter-spacing:1.2px;\n"
"border:2px solid cyan;\n"
"border-radius:10px;\n"
"background:none;\n"
"font-weight:bold;\n"
"color:white;}")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 550, 111, 21))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 255, 219);\n"
"border-radius:10px;\n"
"font: 75 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 83, 255);\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(440, 510, 351, 31))
        self.label_12.setStyleSheet("border:1px solid #ff00ff;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px\n"
"\n"
"\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(660, 20, 61, 61))
        self.label_17.setStyleSheet("background:none;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("User icon.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(610, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;\n"
"background:none;\nfont-size:12px;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(300, 170, 191, 39))
        self.label_9.setStyleSheet("border:1px solid #D86CF7;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(101, 170, 201, 41))
        self.label_10.setStyleSheet("border:1px solid Blue;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(100, 210, 201, 31))
        self.label_14.setStyleSheet("border:1px solid Blue;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(302, 210, 191, 31))
        self.label_13.setStyleSheet("border:1px solid #D86CF7")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(490, 210, 171, 31))
        self.label_15.setStyleSheet("border:1px solid green\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(490, 170, 171, 39))
        self.label_19.setStyleSheet("border:1px solid green;\n"
"font-weight:bold;\n"
"letter-spacing:0.5px;\n"
"font-size:14px")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_16.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.comboBox1.raise_()
        self.label1.raise_()
        self.tableWidget1.raise_()
        self.label_11.raise_()
        self.pushButton4.raise_()
        self.pushButton_3.raise_()
        self.label_12.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.label_19.raise_()
        vcc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vcc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        vcc.setMenuBar(self.menubar)

        self.retranslateUi(vcc)
        QtCore.QMetaObject.connectSlotsByName(vcc)

    def retranslateUi(self, vcc):
        _translate = QtCore.QCoreApplication.translate
        vcc.setWindowTitle(_translate("vcc", "Vaccination Details"))
        self.label_2.setText(_translate("vcc", "Home"))
        self.label_3.setText(_translate("vcc", "Precaution"))
        self.label_4.setText(_translate("vcc", "Latest"))
        self.label_5.setText(_translate("vcc", "Stats"))
        self.pushButton_2.setText(_translate("vcc", "Help Lines"))
        self.label_7.setText(_translate("vcc", "|| Covid Tracker ||"))
        self.label_8.setText(_translate("vcc", "<html><head/><body><p align=\"center\">Show Data</p></body></html>"))
        self.comboBox1.setItemText(0, _translate("vcc", "India"))
        self.comboBox1.setItemText(1, _translate("vcc", "Australia"))
        self.comboBox1.setItemText(2, _translate("vcc", "Russia"))
        self.comboBox1.setItemText(3, _translate("vcc", "China"))
        self.comboBox1.setItemText(4, _translate("vcc", "Canada"))
        self.comboBox1.setItemText(5, _translate("vcc", "Japan"))
        self.label1.setText(_translate("vcc", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">Vaccination Details</span></p></body></html>"))
        self.tableWidget1.setSortingEnabled(False)
        item = self.tableWidget1.verticalHeaderItem(0)
        item.setText(_translate("vcc", "1"))
        item = self.tableWidget1.verticalHeaderItem(1)
        item.setText(_translate("vcc", "2"))
        item = self.tableWidget1.verticalHeaderItem(2)
        item.setText(_translate("vcc", "3"))
        item = self.tableWidget1.verticalHeaderItem(3)
        item.setText(_translate("vcc", "4"))
        item = self.tableWidget1.verticalHeaderItem(4)
        item.setText(_translate("vcc", "5"))
        item = self.tableWidget1.verticalHeaderItem(5)
        item.setText(_translate("vcc", "6"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("vcc", "Country/State"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("vcc", "Total Vaccination"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("vcc", "First Dose"))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("vcc", "Second Dose"))
        __sortingEnabled = self.tableWidget1.isSortingEnabled()
        self.tableWidget1.setSortingEnabled(False)
        item = self.tableWidget1.item(0, 0)
        item.setText(_translate("vcc", "India"))
        item = self.tableWidget1.item(0, 1)
        item.setText(_translate("vcc", "2,80,13,23,08,547"))
        item = self.tableWidget1.item(0, 2)
        item.setText(_translate("vcc", "95,59,26,593"))
        item = self.tableWidget1.item(0, 3)
        item.setText(_translate("vcc", "75,39,33,733"))
        item = self.tableWidget1.item(1, 0)
        item.setText(_translate("vcc", "Australia"))
        item = self.tableWidget1.item(1, 1)
        item.setText(_translate("vcc", "10,75,98,25,876"))
        item = self.tableWidget1.item(1, 2)
        item.setText(_translate("vcc", "82,87,46,376"))
        item = self.tableWidget1.item(1, 3)
        item.setText(_translate("vcc", "60,87,44,847"))
        item = self.tableWidget1.item(2, 0)
        item.setText(_translate("vcc", "Russia"))
        item = self.tableWidget1.item(2, 1)
        item.setText(_translate("vcc", "1,06,25,49,60,982"))
        item = self.tableWidget1.item(2, 2)
        item.setText(_translate("vcc", "89,45,78,698"))
        item = self.tableWidget1.item(2, 3)
        item.setText(_translate("vcc", "73,98,75,479"))
        item = self.tableWidget1.item(3, 0)
        item.setText(_translate("vcc", "China"))
        item = self.tableWidget1.item(3, 1)
        item.setText(_translate("vcc", "1,20,50,65,43,876"))
        item = self.tableWidget1.item(3, 2)
        item.setText(_translate("vcc", "98,78,46,746"))
        item = self.tableWidget1.item(3, 3)
        item.setText(_translate("vcc", "82,74,98,856"))
        item = self.tableWidget1.item(4, 0)
        item.setText(_translate("vcc", "Canada"))
        item = self.tableWidget1.item(4, 1)
        item.setText(_translate("vcc", "8,76,24,68.467"))
        item = self.tableWidget1.item(4, 2)
        item.setText(_translate("vcc", "75,47,86,846"))
        item = self.tableWidget1.item(4, 3)
        item.setText(_translate("vcc", "55,87,67,478"))
        item = self.tableWidget1.item(5, 0)
        item.setText(_translate("vcc", "Japan"))
        item = self.tableWidget1.item(5, 1)
        item.setText(_translate("vcc", "1,10,56,83,67,934"))
        item = self.tableWidget1.item(5, 2)
        item.setText(_translate("vcc", "93,46,85,624"))
        item = self.tableWidget1.item(5, 3)
        item.setText(_translate("vcc", "80,65,87,987"))
        self.tableWidget1.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("vcc", "<html><head/><body><p align=\"center\">Haven\'t Vaccinated Yet? To Book Your Slot</p></body></html>"))
        self.pushButton4.setText(_translate("vcc", "Click Here"))
        self.pushButton_3.setText(_translate("vcc", "Download"))
        self.label_12.setText(_translate("vcc", "<html><head/><body><p align=\"center\">Already Vaccinated? Download Your Certificate</p></body></html>"))
        self.label_18.setText(_translate("vcc", "Welcome, Anurag Yadav"))
        self.label_9.setText(_translate("vcc", "No. of First Doses"))
        self.label_10.setText(_translate("vcc", "Total No. of Vaccinations"))
        self.label_14.setText(_translate("vcc", "11.36 Million"))
        self.label_13.setText(_translate("vcc", "991,769,821"))
        self.label_15.setText(_translate("vcc", "835,538,400"))
        self.label_19.setText(_translate("vcc", "No. of Second Doses"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vcc = QtWidgets.QMainWindow()
    ui = Ui_vcc()
    ui.setupUi(vcc)
    vcc.show()
    sys.exit(app.exec_())
